### PR TITLE
Add Feedhenry Android SDK release 2.3.1

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by johnfriz** [comment]
@wei-lee can you take a look at this PR pls.

**Comment by sebastienblanc** [comment]
Any feedback on this PR ?

**Comment by wei-lee** [comment]
the PR looks ok. Although is there document about how to add new release to this repository?

**Comment by wei-lee** [comment]
perhaps a script to help add new release to this repository will be even better.

**Comment by danielpassos** [comment]
After add it in FH Android SDK project

```
<distributionManagement>
        <repository>
            <id>releases-repo</id>
            <url>https://github.com/feedhenry/fh-android-sdk-repository/raw/master/releases</url>
        </repository>
        <snapshotRepository>
            <id>snapshot-repo</id>
            <url>https://github.com/feedhenry/fh-android-sdk-repository/raw/master/snapshots</url>
        </snapshotRepository>
    </distributionManagement>
```

For create snapshots

```
mvn -DaltDeploymentRepository=snapshot-repo:default::file:[your repo dir]/snapshots clean deploy
```

For create releases

```
mvn -DaltDeploymentRepository=releases-repo:default::file:[your repo dir]/releases clean deploy
```

Then commit it and send a PR

**Comment by wei-lee** [comment]
@danielpassos can you add the above comment into the README of the android sdk repo or this repo?

**Comment by danielpassos** [comment]
@wei-lee https://github.com/danielpassos/fh-android-sdk/commit/b31b13b9d1f9ab435ae4ca026107de57052f82ad Let me know If it's enough

**Comment by wei-lee** [comment]
all good. Feel free to merge this.

**Pull request merged**
